name: build-test
on:
  # main, develop 브랜치를 향해 PR 올리면 빌드 테스트
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

    branches: ['main', 'develop']

# 권한 설정
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  pages: write
  deployments: write

# 동시성 설정
concurrency: preview-${{ github.ref }}

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 종속성 설치 및 프로젝트 빌드
      - name: Install and Build
        run: yarn install && yarn build